# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sharp_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 1
  thymeleaf:
    cache: false
server:
  session-timeout: 1800
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  port: 8282
  uri-encoding: utf-8
#配置日志
logging:
  level:
    root: info
    org.thymeleaf.TemplateEngine: info
    org.springframework.web: info
    cn.vagile.sharp.mapper.UserMapper: trace
mybatis-plus:
  global-config:
    db-config:
      id-type: auto